
services:
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATION_SPLIT_BY_CONTAINER: true
      WATCHTOWER_UPDATE_ON_START: true
      TZ: Europe/Paris

